package route

var httpGatewayTemplate = `
// Code generated by protoc-gen-gateway. DO NOT EDIT.

package gateway

import "protoc-gen-gateway/route"

var routes []route.Info

func RegisterInfo(info route.Info) {
	routes = append(routes, info)
}

func GetInfos() []route.Info {
	return routes
}

func init() {
{{ range . }}
	RegisterInfo(route.Info{
		ServiceName:  "{{.ServiceName}}",
		Method:       "{{.Method}}",
		Pattern:      "{{.Pattern}}",
		RequestType:  "{{.RequestType}}",
		ResponseType: "{{.ResponseType}}",
	})
{{ end }}
}
`

var gqlGatewayTemplate = `
// Code generated by protoc-gen-gateway. DO NOT EDIT.

package gateway

import "protoc-gen-gateway/route"

func init() {
{{ range . }}
	RegisterInfo(route.Info{
		ServiceName:  "{{.ServiceName}}",
		Method:       "{{.Method}}",
		Pattern:      "{{.Pattern}}",
		RequestType:  "{{.RequestType}}",
		ResponseType: "{{.ResponseType}}",
	})
{{ end }}
}
`
