package route

var httpGatewayTemplate = `
// Code generated by protoc-gen-gateway. DO NOT EDIT.

package gateway

import "protoc-gen-gateway/route"

func init() {
{{ range . }}
	route.RegisterInfo(route.Info{
		ServiceName:  "{{.ServiceName}}",
		Method:       "{{.Method}}",
		Pattern:      "{{.Pattern}}",
		RequestType:  "{{.RequestType}}",
		ResponseType: "{{.ResponseType}}",
	})
{{ end }}
}
`

var gqlGatewayTemplate = `
// Code generated by protoc-gen-gateway. DO NOT EDIT.

package gateway

import "protoc-gen-gateway/route"

func init() {
{{ range . }}
	route.RegisterInfo(route.Info{
		ServiceName:  "{{.ServiceName}}",
		Method:       "{{.Method}}",
		Pattern:      "{{.Pattern}}",
		RequestType:  "{{.RequestType}}",
		ResponseType: "{{.ResponseType}}",
	})
{{ end }}
}
`
