package route

import (
	"bytes"
	"fmt"
	"html/template"

	"google.golang.org/protobuf/compiler/protogen"
)

var httpRouteInfoTemplate = `
// Code generated by protoc-gen-gateway. DO NOT EDIT.

package {{.PackageName}}

import "github.com/MonsterYNH/protoc-gen-gateway/route"

func init() {
{{ range .Infos }}
	if err := route.HTTPInfos.RegistInfo(route.Info{
		ServiceName:  "{{.ServiceName}}",
		Type:         "{{.Type}}",
		Method:       "{{.Method}}",
		Pattern:      "{{.Pattern}}",
		RequestType:  "{{.RequestType}}",
		ResponseType: "{{.ResponseType}}",
	}); err != nil {
		panic("route: route regist failed")
	}
{{ end }}
}
`

func generateRouteInfoFile(file *protogen.File, fileSuffix string, plugin *protogen.Plugin, infos []Info) error {
	var buf bytes.Buffer

	tmpl, err := template.New("route_info").Parse(httpRouteInfoTemplate)
	if err != nil {
		return err
	}

	if err := tmpl.Execute(&buf, struct {
		PackageName string
		Infos       []Info
	}{
		PackageName: *file.Proto.Package,
		Infos:       infos,
	}); err != nil {
		return err
	}

	fileName := fmt.Sprintf("%s.%s.%s.go", file.GeneratedFilenamePrefix, fileSuffix, "gateway")
	template := plugin.NewGeneratedFile(fileName, ".")

	template.Write(buf.Bytes())

	return nil
}
